### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by IlyaMokin** [N0menIllisLegio/slack-groupchat-window#1]
@N0menIllisLegio  Thank you. Good attention to details! The task can be closed as accepted! We will be checking JS soon, sorry for delay

**Comment by ilya4321** [comment]
@N0menIllisLegio, actually we don't see you PRs for JS under `dmitry.mukhliada` nickname . did make PRs?

**Comment by N0menIllisLegio** [comment]
Yes, here they are:
https://github.com/N0menIllisLegio/js-assignments/pulls

**Comment by N0menIllisLegio** [comment]
Oops, miss understood task, one moment

**Comment by N0menIllisLegio** [comment]
@IlyaMokin Is it possible to make pull requests if I forked my rep directly from rs? Should I save changes locally, delete rep and fork from yours?

**Comment by N0menIllisLegio** [comment]
<img width="820" alt="Screen Shot 2020-07-19 at 19 33 14" src="https://user-images.githubusercontent.com/33730148/87879985-d7548600-c9f6-11ea-9144-fa46ef9bdec2.png">

**Comment by ilya4321** [comment]
I don't think that you can make PRs to our repository if you didn't fork it

**Comment by N0menIllisLegio** [comment]
@IlyaMokin I have created PRs. Do I need to resend google form?

**Comment by ilya4321** [comment]
No, we will check the PRs
